project: 
  type: website
  output-dir: docs
  
website:
  title: "Distance sampling lab book"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Sampling"
        file: Pr1/sampling.qmd
      - text: "Detn fns"
        file: Pr2/detnfns.qmd
      - text: "Criticism"
        file: Pr3/criticism.qmd
      - text: "Precision"
        file: Pr4/precision.qmd
      - text: "Points"
        file: Pr5/points.qmd

  sidebar:
    - title: "Sampling"
      style: "docked"
      background: light
      contents:
        - Pr1/sampling.qmd
        - Pr1/Pr1-instructions.qmd

    - title: "Detn fns"
      contents:
        - Pr2/detnfns.qmd
        - Pr2/Pr2-instructions.qmd
        - Pr2/truncation-decisions.qmd

    - title: "Criticism"
      contents:
        - Pr3/criticism.qmd
        - Pr3/Pr3-instructions.qmd
        - Pr3/modelsel-demo.qmd

    - title: "Precision"
      contents:
        - Pr4/precision.qmd
        - Pr4/Pr4-instructions.qmd
        - Pr4/left-truncation.qmd

    - title: "Points"
      contents:
        - Pr5/points.qmd
        - Pr5/Pr5-instructions.qmd
        - Pr5/animal_distribution.qmd
        
format:
  html:
    theme: cosmo
    mainfont: Roboto
    fontsize: "12px"
    css: styles.css
    toc: true        
        