project: 
  type: website
  output-dir: docs
  
website:
  title: "Distance sampling lab book"
  navbar:
    background: primary
    search: true
    left:
      - text: "Sampling"
        file: Pr1/sampling.qmd
      - text: "Detection functions"
        file: Pr2/detnfns.qmd
      - text: "Criticism"
        file: Pr3/criticism.qmd
      - text: "Precision"
        file: Pr4/precision.qmd
      - text: "Points"
        file: Pr5/points.qmd
      - text: "Design"
        file: Pr6/design.qmd
      - text: "Strata"
        file: Pr7/strata.qmd
      - text: "Covariates"
        file: Pr8/covariates.qmd
      - text: "Multipliers"
        file: Pr9/multipliers.qmd

  sidebar:
    - title: "Sampling"
      style: "docked"
      background: light
      contents:
        - Pr1/sampling.qmd
        - Pr1/Pr1-instructions.qmd

    - title: "Detection models"
      contents:
        - Pr2/detnfns.qmd
        - Pr2/Pr2-instructions.qmd
        - Pr2/truncation-decisions.qmd

    - title: "Criticism"
      contents:
        - Pr3/criticism.qmd
        - Pr3/Pr3-instructions.qmd
        - Pr3/modelsel-demo.qmd

    - title: "Precision"
      contents:
        - Pr4/precision.qmd
        - Pr4/Pr4-instructions.qmd
        - Pr4/left-truncation.qmd

    - title: "Points"
      contents:
        - Pr5/points.qmd
        - Pr5/Pr5-instructions.qmd
        - Pr5/animal_distribution.qmd
        
    - title: "Design"
      contents: 
        - Pr6/design.qmd
        - Pr6/Pr6-instructions.qmd
        - Pr6/leaflet-demo.qmd
        - Pr6/effort-and-power.qmd
        
    - title: "Strata"
      contents: 
        - Pr7/strata.qmd
        - Pr7/Pr7-instructions.qmd
        - Pr7/detecting-differences.qmd
        
    - title: "Covariates"
      contents: 
        - Pr8/covariates.qmd
        - Pr8/Pr8-instructions.qmd
        - Pr8/Group-size-covariate.qmd
        - Pr8/alternative-selection-metrics.qmd
        
    - title: "Multipliers"
      contents: 
        - Pr9/multipliers.qmd
        
format:
  html:
    theme: sandstone
    mainfont: Verdana
    fontsize: "15px"
    css: styles.css
    toc: true   
    code-copy: true
        