project:
  type: website
  output-dir: docs

website:
  sidebar:
    contents:
      - section: "Welcome"
        contents:
        - index.qmd
      - section: "Practical 1"
        contents: 
        - Pr1/Pr1-instructions.qmd
      - section: "Practical 2"
        contents:
        - Pr2/Pr2-instructions.qmd
        - Pr2/truncation-decisions.qmd
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



