project:
  type: website
  output-dir: docs

website:
  title: "Oct-Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Pr1/*.qmd
      - Pr2/*.qmd
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



