project:
  type: website
  output-dir: docs

website:
  sidebar:
    contents:
      - section: "Welcome"
        contents:
        - index.qmd
      - section: "Practical 1"
        contents: 
        - Pr1/Pr1-instructions.qmd
      - section: "Practical 2"
        contents:
        - Pr2/Pr2-instructions.qmd
        - Pr2/truncation-decisions.qmd
      - section: "Practical 3"
        contents: 
        - Pr3/Pr3-instructions.qmd
        - Pr3/modelsel-demo.qmd
      - section: "Practical 4"
        contents: 
        - Pr4/Pr4-instructions.qmd
        - Pr3/left-truncation.qmd
      - section: "Practical 5"
        contents: 
        - Pr5/Pr5-instructions.qmd
        - Pr5/animal_distribution.qmd
      - about.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



