<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Centre for Research into Ecological and Environmental Modelling   University of St Andrews">
<meta name="dcterms.date" content="2022-10-13">

<title>Distance sampling lab book - Detecting differences in density estimates</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Distance sampling lab book</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../Pr1/sampling.html">Sampling</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Pr2/detnfns.html">Detection functions</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Pr3/criticism.html">Criticism</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Pr4/precision.html">Precision</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Pr5/points.html">Points</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Pr6/design.html">Design</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../Pr7/strata.html" aria-current="page">Strata</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Pr8/covariates.html">Covariates</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Pr9/multipliers.html">Multipliers</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Detecting differences in density estimates</h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Pr7/strata.html" class="sidebar-item-text sidebar-link">Stratification practical 7</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Pr7/Pr7-instructions.html" class="sidebar-item-text sidebar-link">Analysis of stratified survey data</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Pr7/detecting-differences.html" class="sidebar-item-text sidebar-link active">Detecting differences in density estimates</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#estimating-difference-in-density" id="toc-estimating-difference-in-density" class="nav-link active" data-scroll-target="#estimating-difference-in-density">Estimating difference in density</a>
  <ul class="collapse">
  <li><a href="#output-interpretation" id="toc-output-interpretation" class="nav-link" data-scroll-target="#output-interpretation">Output interpretation</a></li>
  </ul></li>
  <li><a href="#appendix-equations-describing-computation-of-estimated-density-differences" id="toc-appendix-equations-describing-computation-of-estimated-density-differences" class="nav-link" data-scroll-target="#appendix-equations-describing-computation-of-estimated-density-differences">Appendix: equations describing computation of estimated density differences</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Detecting differences in density estimates</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Centre for Research into Ecological and Environmental Modelling <br> <strong>University of St Andrews</strong> </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 13, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>##Demonstration</p>
<p>Comparing two density estimates</p>
</div>
</div>
<section id="estimating-difference-in-density" class="level1">
<h1>Estimating difference in density</h1>
<p>Perhaps your study intends not only to estimate density in two strata of your study area, as is the case with the minke whale survey in the Southern Ocean; but also to make inference regarding the magnitude of the difference in densities. That inference could take the form of a significance test or inference based upon an estimated difference and its confidence interval.</p>
<div class="callout-info callout callout-style-default no-icon callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Aside
</div>
</div>
<div class="callout-body-container callout-body">
<p>When I use the term <em>stratum</em>, I could be referring to two geographic strata in your study area. More broadly, strata in an analysis could be two different years of surveys of the same study area, or two species within a study area in a single survey. Depending upon how strata are defined, inferences can be made about differences across space, across time, or between species.</p>
</div>
</div>
<p>I have written a function that computes test statistics and confidence intervals for the difference in estimated densities derived from distance sampling surveys. This function is not part of the <code>Distance</code> package, but is provided in the files associated with Practical 7. As explained in the Appendix below, the nature of the computation depends upon whether the two estimates being compared share a common detection function. As you can imagine, if the estimates share a common detection function, then there is a dependency between the estimates which must be taken into account.</p>
<p>As an example of the comparison of two density estimates, you can perform the calculations upon the minke whale survey data. Notice I have modified the survey data to add observed size of each minke whale group, such that the data to analyse for the density contrast is a superset of the data you analysed in Practical 7 (all else is the same, I’ve simply added a column <code>size</code> for each detection). Hence, the code snippet below begins by reading the data from a CSV file I also include in your RStudio/Cloud workspace for Practical 7.</p>
<p>First, detection functions are fitted to the data set. In the same way as in Practical 7, we fit a pooled detection function, the result placed in the object <code>hazard.pooled</code>. We also split the data by <code>Region.Label</code> and fit separate detection functions to each stratum, resulting in two additional fitted objects: <code>ideal.hr</code> and <code>marginal.hr</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Distance)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>whales <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"stratify_examp.csv"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>hazard.pooled <span class="ot">&lt;-</span> <span class="fu">ds</span>(<span class="at">data=</span>whales, <span class="at">key=</span><span class="st">"hr"</span>, <span class="at">truncation =</span> <span class="fl">1.5</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>ideal.hr <span class="ot">&lt;-</span> <span class="fu">ds</span>(<span class="at">data=</span>whales[whales<span class="sc">$</span>Region.Label<span class="sc">==</span><span class="st">"Ideal"</span>,], <span class="at">key=</span><span class="st">"hr"</span>, <span class="at">truncation=</span><span class="fl">1.5</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>marginal.hr <span class="ot">&lt;-</span> <span class="fu">ds</span>(<span class="at">data=</span>whales[whales<span class="sc">$</span>Region.Label<span class="sc">==</span><span class="st">"Marginal"</span>,], <span class="at">key=</span><span class="st">"hr"</span>, <span class="at">truncation=</span><span class="fl">1.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Code below sources the new function from the file <code>density.difference.ds.r</code> and makes two calls to the function <code>density.difference.ds</code></p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"density.difference.ds.r"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">density.difference.ds</span>(hazard.pooled)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  n.detect  cv.ER line.length n.transects group.size group.size.cv nparm.detect
1       39 0.2323         484          13     2.1538        0.1397            2
2       49 0.3724        1370          12     2.3265        0.2303            2
   D.hat D.hat.cv     f0   f0cv
1 0.0929   0.2916 1.0711 0.1073
2 0.0446   0.4508 1.0711 0.1073
  D1.minus.D2 SE.difference t.statistic df.t.stat P.value     LCB    UCB
1      0.0484        0.0402      1.2048   49.2919   0.234 -0.0323 0.1291</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">density.difference.ds</span>(ideal.hr, marginal.hr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  n.detect  cv.ER line.length n.transects group.size group.size.cv nparm.detect
1       39 0.2323         484          13     2.1538        0.1397            2
2       49 0.3724        1370          12     2.3265        0.2303            2
   D.hat D.hat.cv     f0   f0cv
1 0.1167   0.3182 1.3450 0.1338
2 0.0365   0.4451 0.8781 0.1315
  D1.minus.D2 SE.difference t.statistic df.t.stat P.value     LCB    UCB
1      0.0802        0.0405      1.9779   27.6636   0.058 -0.0029 0.1633</code></pre>
</div>
</div>
<section id="output-interpretation" class="level2">
<h2 class="anchored" data-anchor-id="output-interpretation">Output interpretation</h2>
<p>The first two lines of output echo much of the input information: number of detections, encounter rate CV, line length, number of transects, average group size, CV of average groups size, number of parameters in the detection function. Also echoed are the stratum-specific density estimates and their CV along with the estimate of the <span class="math inline">\(f(0)\)</span> parameter of the detection function and its CV.</p>
<p>The last line of output shows the difference of estimated densities and its standard error. Following this is the test statistic which is distributed as a t-statistic (Eqn @ref(eq:tstat)) and its associated degrees of freedom (Eqn @ref(eq:testdf)) and an associated significance level for a two-tailed test. The final pair of values are the bounds of the confidence interval on the estimated difference computed from Eqn (@ref(eq:tconfint)).</p>
<p><em>Note:</em> When a pooled detection function is used, the difference is relatively small (~0.05) and non-significant. When separate detection functions are used, the magnitude of the estimated difference increases (~0.08), with a standard error of roughly the same magnitude. Quite a few degrees of freedom are lost by having to estimate two additional parameters from separate detection functions. The total width of the confidence interval changes little (0.1662 for separate detection functions versus 0.1614 for pooled detection function). However because of the shift in the estimated difference from 0.0484 to 0.0802, the significance level shifts from 0.234 to 0.058.</p>
<p><em>Lesson for survey design:</em> The uncertainty in all of the density estimates come from encounter rate variability. If the purpose of the study was to demonstrate a difference in density between these strata, a better survey design, with more than 13 and 12 transects would have been required to produce better estimates of stratum-specific encounter rate uncertainty.</p>
</section>
</section>
<section id="appendix-equations-describing-computation-of-estimated-density-differences" class="level1">
<h1>Appendix: equations describing computation of estimated density differences</h1>
<p><em>This is Section 3.6.5 of Buckland et al.&nbsp;(2001)</em></p>
<p>Frequently, we wish to draw inference on change in density over time, or difference in density between habitats. We consider here simple comparisons between two density estimates.</p>
<p>Consider two density estimates, <span class="math inline">\(\hat{D}_{1}\)</span> and <span class="math inline">\(\hat{D}_{2} .\)</span> Suppose first that they are independently estimated. We then estimate the difference in density by <span class="math inline">\(\hat{D}_{1}-\hat{D}_{2}\)</span> with variance <span class="math display">\[\begin{equation}
\widehat{\operatorname{var}}\left(\hat{D}_{1}-\hat{D}_{2}\right)=\widehat{\operatorname{var}}\left(\hat{D}_{1}\right)+\widehat{\operatorname{var}}\left(\hat{D}_{2}\right)
(\#eq:vardiff)
\end{equation}\]</span> Distance provides approximate degrees of freedom <span class="math inline">\(\mathrm{df}_{1}\)</span> for <span class="math inline">\(\hat{D}_{1}\)</span> and <span class="math inline">\(\mathrm{df}_{2}\)</span> for <span class="math inline">\(\hat{D}_{2},\)</span> based on Satterthwaite’s approximation. We can use these to obtain an approximate <span class="math inline">\(t\)</span>-statistic:<br>
[ T= t_{} (#eq:tstat) ] where [ (#eq:testdf) ]</p>
<p>Provided df are around 30 or more, the simpler <span class="math inline">\(z\)</span>-statistic provides a good approximation: [ Z= N(0,1) (#eq:zstat) ] For either statistic, we can test the null hypothesis <span class="math inline">\(H_{0}: D_{1}=D_{2}\)</span> by substituting <span class="math inline">\(D_{1}-D_{2}=0\)</span> in eqn @ref(eq:tstat) or @ref(eq:zstat), and looking at the resulting value in <span class="math inline">\(t\)</span>-tables or <span class="math inline">\(z\)</span>-tables. Approximate <span class="math inline">\(100(1-2 \alpha) \%\)</span> confidence limits for <span class="math inline">\(\left(D_{1}-D_{2}\right)\)</span> are given by [ (<em>{1}-</em>{2}) t_{}() (#eq:tconfint) ]</p>
for df <span class="math inline">\(&lt;30,\)</span> or [ (<em>{1}-</em>{2}) z() <br>
(#eq:zconfint) ] otherwise. Often, a single detection function is fitted to pooled data, so that [ <em>{1}= </em>{2}= (#eq:dcommon) ] (where the terms <span class="math inline">\(\hat{E}_{i}(s)\)</span> are omitted if the objects are not in clusters). Because <span class="math inline">\(\hat{f}(0)\)</span> appears in both equations, we can no longer assume that <span class="math inline">\(\hat{D}_{1}\)</span> and <span class="math inline">\(\hat{D}_{2}\)</span> are independent. Instead, we can write [ <em>{i}=</em>{i} (0), i=1,2 (#eq:dwithm) ] where [ <em>{i}= (#eq:mdefn) ] As the <span class="math inline">\(M_{i}\)</span> are independently estimated, and are assumed to be independent of <span class="math inline">\(\hat{f}(0),\)</span> we can now find the variance of <span class="math inline">\(\hat{D}_{1}-\hat{D}_{2}\)</span> using the delta method: [ </em>{1}-<em>{2}=(</em>{1}-_{2}) (0) (#eq:diffusingm) ] so that [
<span class="math display">\[\begin{aligned}
\widehat{\operatorname{var}}\left(\hat{D}_{1}-\hat{D}_{2}\right) &amp;=\left(\hat{D}_{1}-\hat{D}_{2}\right)^{2}\left[\frac{\widehat{\operatorname{var}}\left(\hat{M}_{1}-\hat{M}_{2}\right)}{\left(\hat{M}_{1}-\hat{M}_{2}\right)^{2}}+\frac{\widehat{\operatorname{var}}\{\hat{f}(0)\}}{\{\hat{f}(0)\}^{2}}\right] \\
&amp;=\{\hat{f}(0)\}^{2} \widehat{\operatorname{var}}\left(\hat{M}_{1}-\hat{M}_{2}\right)+\left(\hat{M}_{1}-\hat{M}_{2}\right)^{2} \widehat{var}\{\hat{f}(0)\}
\end{aligned}\]</span>
<p>(#eq:varwithm) ] where [ (<em>{1}-</em>{2})=(<em>{1})+(</em>{2}) (#eq:varmdiff) ] and [ (<em>{i})=</em>{i}^{2}, i=1,2 (#eq:varm) ] Note that the second form of eqn @ref(eq:varwithm) still applies when <span class="math inline">\(\left(\hat{M}_{1}-\hat{M}_{2}\right)=0,\)</span> whereas the first form leads to a ratio of zero over zero. Inference can now proceed as before, either with additional applications of Satterthwaite’s approximation in conjunction with eqn @ref(eq:tstat) if an approximate <span class="math inline">\(t\)</span>-statistic is required, or more usually, by straightforward application of eqn @ref(eq:zstat).</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>