<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Centre for Research into Ecological and Environmental Modelling   University of St Andrews">
<meta name="dcterms.date" content="2022-12-01">

<title>Distance sampling lab book - Analysis with multipliers solution</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Distance sampling lab book</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../Pr1/sampling.html">Sampling</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Pr2/detnfns.html">Detection functions</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Pr3/criticism.html">Criticism</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Pr4/precision.html">Precision</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Pr5/points.html">Points</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Pr6/design.html">Design</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Pr7/strata.html">Strata</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Pr8/covariates.html">Covariates</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../Pr9/multipliers.html" aria-current="page">Multipliers</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../extras/extras.html">Extras</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title">Analysis with multipliers <strong>solution</strong></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Pr9/multipliers.html" class="sidebar-item-text sidebar-link">Multipliers practical 9</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Pr9/Pr9-instructions.html" class="sidebar-item-text sidebar-link">Analyses using multipliers</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Pr9/multi-analysis.html" class="sidebar-item-text sidebar-link">Multispecies and multisession distance sampling analysis</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Pr9/countmodel-lines.html" class="sidebar-item-text sidebar-link">Effect of habitat covariate upon estimated density—lines</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Pr9/countmodel-points.html" class="sidebar-item-text sidebar-link">Effect of habitat covariate upon estimated density–points</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../Pr9/Prac9_solution.html" class="sidebar-item-text sidebar-link active">Analysis with multipliers <strong>solution</strong></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#dung-survey-of-deer" id="toc-dung-survey-of-deer" class="nav-link active" data-scroll-target="#dung-survey-of-deer">Dung survey of deer</a></li>
  <li><a href="#estimating-decay-rate-from-data" id="toc-estimating-decay-rate-from-data" class="nav-link" data-scroll-target="#estimating-decay-rate-from-data">Estimating decay rate from data</a></li>
  <li><a href="#cue-counting-survey-of-whales" id="toc-cue-counting-survey-of-whales" class="nav-link" data-scroll-target="#cue-counting-survey-of-whales">Cue counting survey of whales</a></li>
  <li><a href="#cue-counting-survey-of-songbirds-optional" id="toc-cue-counting-survey-of-songbirds-optional" class="nav-link" data-scroll-target="#cue-counting-survey-of-songbirds-optional">Cue counting survey of songbirds (optional)</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Analysis with multipliers <strong>solution</strong></h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Centre for Research into Ecological and Environmental Modelling <br> <strong>University of St Andrews</strong> </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 1, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Solution
</div>
</div>
<div class="callout-body-container callout-body">
<p>Analysis with multipliers</p>
</div>
</div>
<section id="dung-survey-of-deer" class="level1">
<h1>Dung survey of deer</h1>
<p>Returning to the data described in <span class="citation" data-cites="marques2001">(<a href="#ref-marques2001" role="doc-biblioref">Marques et al., 2001</a>)</span>, the following code loads the relevant packages and data. The perpendicular distances are measured in centimetres, effort along the transects measured in kilometres and areas in square kilometres.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(Distance)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(sikadeer)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>conversion.factor <span class="ot">&lt;-</span> <span class="fu">convert_units</span>(<span class="st">"centimeter"</span>, <span class="st">"kilometer"</span>, <span class="st">"square kilometer"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Here we did not perform a comprehensive examination of fitting a detection function to the detected pellet groups, however, as a general guideline, we truncated the longest 10% perpendicular distances.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>deer.df <span class="ot">&lt;-</span> <span class="fu">ds</span>(sikadeer, <span class="at">key=</span><span class="st">"hn"</span>, <span class="at">truncation=</span><span class="st">"10%"</span>, <span class="at">convert_units =</span> conversion.factor)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(deer.df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Prac9_solution_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(deer.df<span class="sc">$</span>dht<span class="sc">$</span>individuals<span class="sc">$</span>summary)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Region Area CoveredArea Effort    n  k        ER      se.ER     cv.ER
1      A 13.9    0.005950   1.70 1217 13 715.88234 119.918872 0.1675120
2      B 10.3    0.003850   1.10  396 10 359.99999  86.859289 0.2412758
3      C  8.6    0.001575   0.45   17  3  37.77778   8.521202 0.2255612
4      E  8.0    0.002975   0.85   30  5  35.29412  16.568939 0.4694533
5      F 14.0    0.000700   0.20   29  1 145.00000   0.000000 0.0000000
6      G 15.2    0.001400   0.40   32  3  80.00000  39.686269 0.4960784
7      H 11.3    0.000700   0.20    3  1  15.00000   0.000000 0.0000000
8      J  9.6    0.000350   0.10    7  1  70.00000   0.000000 0.0000000
9  Total 90.9    0.017500   5.00 1731 37 201.90876   0.000000 0.0000000</code></pre>
</div>
</div>
<p>The summary above shows that in blocks F, H and J there was only one transect and, as a consequence, it is not possible to calculate a variance empirically for the encounter rate in those blocks.</p>
</section>
<section id="estimating-decay-rate-from-data" class="level1">
<h1>Estimating decay rate from data</h1>
<p>A paper by <span class="citation" data-cites="Laietal03">Laing et al. (<a href="#ref-Laietal03" role="doc-biblioref">2003</a>)</span> describes field protocol for collecting data to estimate the mean persistence time of dung or nests to be used as multipliers. The code segment shown earlier analyses a file of such data via logistic regression to produce an estimate of mean persistence time and its associated uncertainty.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Prac9_solution_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Mean persistence time                    SE                   %CV 
           163.396748             14.226998              8.707026 </code></pre>
</div>
</div>
<p>Using the output from calling the <code>MIKE.persistence</code> function, the multipliers can be specified:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create list of multipliers</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>mult <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">creation =</span> <span class="fu">data.frame</span>(<span class="at">rate=</span><span class="dv">25</span>, <span class="at">SE=</span><span class="dv">0</span>),</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>             <span class="at">decay    =</span> <span class="fu">data.frame</span>(<span class="at">rate=</span><span class="dv">163</span>, <span class="at">SE=</span><span class="dv">14</span>))</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mult)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$creation
  rate SE
1   25  0

$decay
  rate SE
1  163 14</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>deer_ests <span class="ot">&lt;-</span> <span class="fu">dht2</span>(deer.df, <span class="at">flatfile=</span>sikadeer, <span class="at">strat_formula=</span><span class="sc">~</span>Region.Label,</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>                  <span class="at">convert_units=</span>conversion.factor, <span class="at">multipliers=</span>mult, </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>                  <span class="at">stratification=</span><span class="st">"effort_sum"</span>, <span class="at">total_area =</span> <span class="dv">100</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(deer_ests, <span class="at">report=</span><span class="st">"abundance"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Abundance estimates from distance sampling
Stratification : effort_sum 
Variance       : R2, n/L 
Multipliers    : creation, decay 
Sample fraction : 1 


Summary statistics:
 Region.Label  Area CoveredArea Effort    n  k      ER   se.ER cv.ER
            A  13.9    0.005950   1.70 1217 13 715.882 119.919 0.168
            B  10.3    0.003850   1.10  396 10 360.000  86.859 0.241
            C   8.6    0.001575   0.45   17  3  37.778   8.521 0.226
            E   8.0    0.002975   0.85   30  5  35.294  16.569 0.469
            F  14.0    0.000700   0.20   29  1 145.000   0.000 0.000
            G  15.2    0.001400   0.40   32  3  80.000  39.686 0.496
            H  11.3    0.000700   0.20    3  1  15.000   0.000 0.000
            J   9.6    0.000350   0.10    7  1  70.000   0.000 0.000
        Total 100.0    0.017500   5.00 1731 37 346.200  45.234 0.131

Abundance estimates:
 Region.Label Estimate      se    cv  LCI  UCI        df
            A     1027 197.474 0.192  691 1527    20.797
            B      383  99.171 0.259  220  667    11.955
            C       34   8.200 0.244   15   75     2.759
            E       29  13.959 0.479    9   99     4.329
            F      210  19.752 0.094  174  252 60314.199
            G      126  63.399 0.505   18  858     2.147
            H       18   1.649 0.094   15   21 60314.199
            J       69   6.539 0.094   58   83 60314.199
        Total     3575 575.860 0.161 2560 4990    20.215

Component percentages of variance:
 Region.Label Detection    ER Multipliers
            A      4.07 75.96       19.97
            B      2.24 86.76       10.99
            C      2.52 85.14       12.34
            E      0.66 96.13        3.22
            F     16.93  0.00       83.07
            G      0.59 96.52        2.89
            H     16.93  0.00       83.07
            J     16.93  0.00       83.07
        Total      8.09 91.91        0.00</code></pre>
</div>
</div>
<p>There are a few things to notice:</p>
<ul>
<li>overall estimate of density
<ul>
<li>most effort took place in woodland A where deer density was high. Therefore, the overall estimate is between the estimated density in woodland A and the lower densities in the other woodlands.</li>
</ul></li>
<li>components of variance
<ul>
<li>we now have uncertainty associated with the encounter rate, detection function and decay rate (note there was no uncertainty associated with the production rate) and so the components of variation for all three components are provided.</li>
</ul></li>
</ul>
<p>In woodland A, there were 13 transects on which over 1,200 pellet groups were detected: uncertainty in the estimated density was 19% and the variance components were apportioned as detection probability 4%, encounter rate 76% and multipliers 20%.</p>
<p>In woodland E, there were 5 transects and 30 pellet groups resulting in a coefficient of variation (CV) of 48%: the variance components were apportioned as detection probability 0.7%, encounter rate 96% and multipliers 3%.</p>
<p>In woodland F only a single transect was placed and the CV of density of 9% was apportioned as detection probability 17% and multipliers 83%. Do you trust this assessment of uncertainty in the density of deer in this woodland? We are missing a component of variation because we were negligent in placing only a single transect in this woodland and so are left to ‘assume’ there is no variability in encounter rate in this woodland.</p>
<p>By the same token, we are left to assume there is no variability in production rates between deer because we have not included a measure of uncertainty in this facet of our analysis.</p>
</section>
<section id="cue-counting-survey-of-whales" class="level1">
<h1>Cue counting survey of whales</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(CueCountingExample)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(CueCountingExample, <span class="at">n=</span><span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Region.Label  Area Sample.Label Cue.rate Cue.rate.SE Cue.rate.df object distance
1            B 85000         2.18       25           5           1     NA       NA
2            B 85000         2.19       25           5           1     NA       NA
3            B 85000         2.20       25           5           1     NA       NA
  Sample.Fraction Sample.Fraction.SE Search.time bss   sp size Study.Area
1             0.5                  0   0.1333333  NA &lt;NA&gt;   NA     whales
2             0.5                  0   0.1000000  NA &lt;NA&gt;   NA     whales
3             0.5                  0   0.4333333  NA &lt;NA&gt;   NA     whales</code></pre>
</div>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>CueCountingExample<span class="sc">$</span>Effort <span class="ot">&lt;-</span> CueCountingExample<span class="sc">$</span>Search.time</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>cuerates <span class="ot">&lt;-</span> CueCountingExample[ ,<span class="fu">c</span>(<span class="st">"Cue.rate"</span>, <span class="st">"Cue.rate.SE"</span>, <span class="st">"Cue.rate.df"</span>)]</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>cuerates <span class="ot">&lt;-</span> <span class="fu">unique</span>(cuerates)</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(cuerates) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"rate"</span>, <span class="st">"SE"</span>, <span class="st">"df"</span>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>mult <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">creation=</span>cuerates)</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mult)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$creation
  rate SE df
1   25  5  1</code></pre>
</div>
</div>
<p>The estimated cue rate, <span class="math inline">\(\hat \nu\)</span>, is 25 cues per unit time (per hour in this case). Its standard error is 5, therefore the CV of cue rate is <span class="math inline">\(5/25 = 0.2\)</span> (20%).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tidy up data by removing surplus columns</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>CueCountingExample[ ,<span class="fu">c</span>(<span class="st">"Cue.rate"</span>, <span class="st">"Cue.rate.SE"</span>, <span class="st">"Cue.rate.df"</span>, <span class="st">"Sample.Fraction"</span>, </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                       <span class="st">"Sample.Fraction.SE"</span>)] <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="cn">NULL</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>trunc <span class="ot">&lt;-</span> <span class="fl">1.2</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>whale.df.hn <span class="ot">&lt;-</span> <span class="fu">ds</span>(CueCountingExample, <span class="at">key=</span><span class="st">"hn"</span>, <span class="at">transect=</span><span class="st">"point"</span>, <span class="at">adjustment=</span><span class="cn">NULL</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>                  <span class="at">truncation=</span>trunc)</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>whale.df.hr <span class="ot">&lt;-</span> <span class="fu">ds</span>(CueCountingExample, <span class="at">key=</span><span class="st">"hr"</span>, <span class="at">transect=</span><span class="st">"point"</span>, <span class="at">adjustment=</span><span class="cn">NULL</span>,</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>                  <span class="at">truncation=</span>trunc)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">summarize_ds_models</span>(whale.df.hn, whale.df.hr), <span class="at">digits =</span> <span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped">
<colgroup>
<col style="width: 22%">
<col style="width: 13%">
<col style="width: 8%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 16%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: left;">Key function</th>
<th style="text-align: left;">Formula</th>
<th style="text-align: right;">C-vM p-value</th>
<th style="text-align: right;"><span class="math inline">\(\hat{P_a}\)</span></th>
<th style="text-align: right;">se(<span class="math inline">\(\hat{P_a}\)</span>)</th>
<th style="text-align: right;"><span class="math inline">\(\Delta\)</span>AIC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Half-normal</td>
<td style="text-align: left;">~1</td>
<td style="text-align: right;">0.810</td>
<td style="text-align: right;">0.239</td>
<td style="text-align: right;">0.043</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Hazard-rate</td>
<td style="text-align: left;">~1</td>
<td style="text-align: right;">0.747</td>
<td style="text-align: right;">0.281</td>
<td style="text-align: right;">0.065</td>
<td style="text-align: right;">3.07</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Half the circle (point transect) was searched and so the sampling fraction <span class="math inline">\(\phi /2\pi = 0.5\)</span>. Therefore, <span class="math inline">\(\phi = \pi\)</span> (<span class="math inline">\(\phi\)</span> must be in radians).</p>
<p>The following commands obtain density estimates assuming no stratification (<code>strat_formula=~1</code>).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>whale.est.hn <span class="ot">&lt;-</span> <span class="fu">dht2</span>(whale.df.hn, <span class="at">flatfile=</span>CueCountingExample, <span class="at">strat_formula=</span><span class="sc">~</span><span class="dv">1</span>, </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">multipliers=</span>mult, <span class="at">sample_fraction=</span><span class="fl">0.5</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(whale.est.hn, <span class="at">report=</span><span class="st">"abundance"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Abundance estimates from distance sampling
Stratification : geographical 
Variance       : P2, n/L 
Multipliers    : creation 
Sample fraction : 0.5 


Summary statistics:
 .Label   Area CoveredArea Effort  n  k    ER se.ER cv.ER
  Total 168000     82.4932  36.47 40 92 1.097 0.303 0.276

Abundance estimates:
 .Label Estimate       se    cv  LCI   UCI     df
  Total    13654 5263.071 0.385 6112 30500 13.058

Component percentages of variance:
 .Label Detection    ER Multipliers
  Total      21.7 51.38       26.92</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>whale.est.hr <span class="ot">&lt;-</span> <span class="fu">dht2</span>(whale.df.hr, <span class="at">flatfile=</span>CueCountingExample, <span class="at">strat_formula=</span><span class="sc">~</span><span class="dv">1</span>, </span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>                     <span class="at">multipliers=</span>mult, <span class="at">sample_fraction=</span><span class="fl">0.5</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(whale.est.hr, <span class="at">report=</span><span class="st">"abundance"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Abundance estimates from distance sampling
Stratification : geographical 
Variance       : P2, n/L 
Multipliers    : creation 
Sample fraction : 0.5 


Summary statistics:
 .Label   Area CoveredArea Effort  n  k    ER se.ER cv.ER
  Total 168000     82.4932  36.47 40 92 1.097 0.303 0.276

Abundance estimates:
 .Label Estimate       se    cv  LCI   UCI     df
  Total    11590 4777.034 0.412 5017 26774 16.593

Component percentages of variance:
 .Label Detection    ER Multipliers
  Total     31.52 44.93       23.54</code></pre>
</div>
</div>
<p>A half normal detection function was chosen and whale abundance was estimated to be 13,654 whales with a 95% confidence interval (6,112: 30,500).</p>
<p>Note the large difference between the half normal estimate and the estimate from the hazard rate model, which is 11,590 whales, with 95% confidence interval (5,017; 26773). Remember that the key parameter in a cue counting analysis is <span class="math inline">\(h(0)\)</span>, the slope of the fitted pdf to the observed data at distance zero. The difference between the estimates for the different key function is the difference between these slopes for the two models (Fig. 2):</p>
<div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(whale.df.hn, <span class="at">pdf=</span><span class="cn">TRUE</span>, <span class="at">main=</span><span class="st">"Half normal"</span>)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(whale.df.hr, <span class="at">pdf=</span><span class="cn">TRUE</span>, <span class="at">main=</span><span class="st">"Hazard rate"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Prac9_solution_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Half normal PDF</figcaption><p></p>
</figure>
</div>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Prac9_solution_files/figure-html/unnamed-chunk-9-2.png" class="img-fluid figure-img" width="672"></p>
<p></p><figcaption class="figure-caption">Hazard rate PDF</figcaption><p></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<p>Cue counting estimates of detection probability are more volatile than those from line transect surveys, because on a cue counting survey you have few data where you need it most to estimate <span class="math inline">\(h(0)\)</span> - namely at distances close to zero. As a consequence, cue-counting surveys require higher cue sample size for reliable estimation than samples of animals for line transect surveys.</p>
<p>Don’t worry too much about the apparent lack of fit in the first interval, or two, in Figure 2 - remember the sample size is very small in these intervals. Use the plot above and the goodness-of-fit statistics to guide you about the fit of your model.</p>
</section>
<section id="cue-counting-survey-of-songbirds-optional" class="level1">
<h1>Cue counting survey of songbirds (optional)</h1>
<p>Analysis of the cue count data of winter wrens described by <span class="citation" data-cites="buckland2006">Buckland (<a href="#ref-buckland2006" role="doc-biblioref">2006</a>)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(wren_cuecount)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>cuerate <span class="ot">&lt;-</span> <span class="fu">unique</span>(wren_cuecount[ , <span class="fu">c</span>(<span class="st">"Cue.rate"</span>,<span class="st">"Cue.rate.SE"</span>)])</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(cuerate) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"rate"</span>, <span class="st">"SE"</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>mult <span class="ot">&lt;-</span> <span class="fu">list</span>(<span class="at">creation=</span>cuerate)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mult)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$creation
    rate     SE
1 1.4558 0.2428</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Search time is the effort - this is 2 * 5min visits</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>wren_cuecount<span class="sc">$</span>Effort <span class="ot">&lt;-</span> wren_cuecount<span class="sc">$</span>Search.time</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>w3.hr <span class="ot">&lt;-</span> <span class="fu">ds</span>(wren_cuecount, <span class="at">transect=</span><span class="st">"point"</span>, <span class="at">key=</span><span class="st">"hr"</span>, <span class="at">adjustment=</span><span class="cn">NULL</span>, <span class="at">truncation=</span><span class="fl">92.5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The sampling fraction for these data will be 1 because the full circle around the observer was searched.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>conversion.factor <span class="ot">&lt;-</span> <span class="fu">convert_units</span>(<span class="st">"meter"</span>, <span class="cn">NULL</span>, <span class="st">"hectare"</span>)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>w3.est <span class="ot">&lt;-</span> <span class="fu">dht2</span>(w3.hr, <span class="at">flatfile=</span>wren_cuecount, <span class="at">strat_formula=</span><span class="sc">~</span><span class="dv">1</span>,</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>               <span class="at">multipliers=</span>mult, <span class="at">convert_units=</span>conversion.factor)</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="co"># NB "Effort" here is sum(Search.time) in minutes</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># NB "CoveredArea" here is pi * w^2 * sum(Search.time)</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(w3.est, <span class="at">report=</span><span class="st">"density"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Density estimates from distance sampling
Stratification : geographical 
Variance       : P2, n/L 
Multipliers    : creation 
Sample fraction : 1 


Summary statistics:
 .Label Area CoveredArea Effort   n  k    ER se.ER cv.ER
  Total 33.2    860.1681    320 765 32 2.391 0.236 0.099

Density estimates:
 .Label Estimate    se  cv    LCI    UCI      df
  Total   1.2092 0.242 0.2 0.8195 1.7843 522.541

Component percentages of variance:
 .Label Detection    ER Multipliers
  Total      6.14 24.33       69.54</code></pre>
</div>
</div>
<p>Note the large proportion of the uncertainty in winter wren density stems from variability in cue (song) rate. Analyses of the cue count data are necessarily rather subjective as the data show substantial over-dispersion (a single bird may give many song bursts all from the same location during a five minute count). In this circumstance, goodness-of-fit tests are misleading and care must be taken not to over-fit the data (i.e.&nbsp;fit a complicated detection function).</p>
<div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(w3.hr, <span class="at">pdf=</span><span class="cn">TRUE</span>, <span class="at">main=</span><span class="st">"Cue distances of winter wren."</span>)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">gof_ds</span>(w3.hr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell quarto-layout-panel">
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Prac9_solution_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="Prac9_solution_files/figure-html/unnamed-chunk-12-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="quarto-layout-row quarto-layout-valign-top">
<div class="cell-output cell-output-stdout quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<pre><code>
Goodness of fit results for ddf object

Distance sampling Cramer-von Mises test (unweighted)
Test statistic = 1.70062 p-value = 6.04794e-05</code></pre>
</div>
</div>
</div>
</div>
</section>
<section id="references" class="level1">




</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-line-spacing="2" role="doc-bibliography">
<div id="ref-buckland2006" class="csl-entry" role="doc-biblioentry">
Buckland, S. T. (2006). Point-transect surveys for songbirds: Robust methodologies. <em>The Auk</em>, <em>123</em>(2), 345–357. <a href="https://doi.org/10.1642/0004-8038(2006)123[345:PSFSRM]2.0.CO;2">https://doi.org/10.1642/0004-8038(2006)123[345:PSFSRM]2.0.CO;2</a>
</div>
<div id="ref-Laietal03" class="csl-entry" role="doc-biblioentry">
Laing, S. E., Buckland, S. T., Burn, R. W., Lambie, D., &amp; Amphlett, A. (2003). Dung and nest surveys: Estimating decay rate. <em>Journal of Applied Ecology</em>, <em>40</em>, 1102–1111. <a href="https://doi.org/10.1111/j.1365-2664.2003.00861.x">https://doi.org/10.1111/j.1365-2664.2003.00861.x</a>
</div>
<div id="ref-marques2001" class="csl-entry" role="doc-biblioentry">
Marques, F. F. C., Buckland, S. T., Goffin, D., Dixon, C. E., Borchers, D. L., Mayle, B. A., &amp; Peace, A. J. (2001). Estimating deer abundance from line transect surveys of dung: sika deer in southern Scotland. <em>Journal of Applied Ecology</em>, <em>38</em>(2), 349–363. <a href="https://doi.org/10.1046/j.1365-2664.2001.00584.x">https://doi.org/10.1046/j.1365-2664.2001.00584.x</a>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>