---
title: How to use tutorials
description: Tutorials accompany most practicals. They provide you with simple self-assessment of your understanding of main messages of the practicals.
author: 
  - name: Eric Rexstad
date: 12-29-2022
image: https://images.unsplash.com/photo-1586943759074-f741c014c5d9?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8dHV0b3JpYWx8ZW58MHx8MHx8&auto=format&fit=crop&w=400&q=60
draft: false
---

While I intend to discuss the solutions to every practical, I want you to have the opportunity to do some self-assessment either before we discuss the solution together, or if you choose to return to a practical sometime in the future.

I have created a few short answer/multiple choice questions to accompany Practicals 2-8. These tutorials re-create output from the practicals and ask you to interpret that output.

In some tutorials, I ask you to complete a short bit of R code to perform some calculations (hints are provided to help you do this). In all tutorials I ask you to step back from pouring over output and ask to to make biological interpretations.

# Where to find the practicals

Open the `Tutorial` tab of the upper right Posit/cloud pane. You will see a number of tutorial titles. Those relevant to you have the label

`introtutor: pracX` 

under the tutorial title, where `X` is the number of the workshop practical to which the tutorial pertains.


# How to complete the practicals

Press `Start Tutorial` in the Tutorial tab of the upper right Posit/cloud pane. In pressing this button, you may see code execution messages in the `Background Jobs` tab of the lower left pane.  Eventually (for some tutorials you may need to be patient), the tutorial will appear in the upper right pane.  There is a small icon at the top of this pane showing an arrow and window; press this if you wish the tutorial to pop out of the pane and open a new window.

## Don't worry about selecting incorrect answers

There is no "grade" associated with these practicals. The answers you provide cannot be seen by me or your fellow participants. The practicals offer you another opportunity to explore distance sampling analyses. You can assess the results of your explorations through using the practicals.

Use of the practicals is completely optional. If they help you learn about distance sampling analyses, by all means use them. If they interfere with your learning, concentrate on other facets of the workshop materials.
