---
title: Literature critique of distance sampling papers
---

In addition to understanding how to conduct distance sampling surveys that are defensible and robust, I want you also to detect reinforcement and threats to robust inference in published distance sampling studies. I provide you with examples of three recently published distance sampling studies.

I ask that you select one of these papers and invest 30 minutes in scanning the methods and results sections, understanding what they have done and asking yourself if there is anything you would disagree with in their approach or conclusions. Do they provide evidence to support the conclusions they present?

I've found a few papers representing three taxonomic groups: terrestrial mammals, terrestrial birds and marine mammals.  Select a paper of interest to you and create a list of positive and negative aspects of the way in which the design and analysis are reported.  Do you feel the results are defensible in light of the methodology employed and described?

- Buuveibaatar, B., Strindberg, S., Kaczensky, P., Payne, J., Chimeddorj, B., Naranbaatar, G., Amarsaikhan, S., Dashnyam, B., Munkhzul, T., Purevsuren, T., Hosack, D. A., & Fuller, T. K. (2017). Mongolian Gobi supports the world’s largest populations of khulan *Equus hemionus* and goitered gazelles *Gazella subgutturosa*. Oryx 51(4):639–647. [https://doi.org/10.1017/S0030605316000417](https://doi.org/10.1017/S0030605316000417)
- Zelelew, S. A., Bekele, A., & Archibald, G. (2020). Detection function, cluster size, density, and population size of Black Crowned Crane *Balearica pavonina ceciliae* in the upper Blue Nile River, Lake Tana area. Scientific African 10:e00557. [https://doi.org/10.1016/j.sciaf.2020.e00557](https://doi.org/10.1016/j.sciaf.2020.e00557)
- Strindberg, S., Ersts, P. J., Collins, T., Sounguet, G.-P., & Rosenbaum, H. C. (2020). Line transect estimates of humpback whale abundance and distribution on their wintering grounds in the coastal waters of Gabon. J. Cetacean Res. Manage. 153–160. [https://doi.org/10.47536/jcrm.vi3.324](https://doi.org/10.47536/jcrm.vi3.324)
- Syahrullah, F. N., Maddus, U., Mustari, A. H., Gursky, S., & Indrawan, M. (2023). Distribution and abundance of Peleng Tarsier *(Tarsius pelengensis)* in Banggai Island group, Indonesia. Scientific Reports, 13(1), Article 1. [https://doi.org/10.1038/s41598-023-30049-5](https://doi.org/10.1038/s41598-023-30049-5)
